//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chains.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListItemDefaultCollection
    {
        public System.Guid CheckListItemId { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
    }
}
