//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chains.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.PropertyCheckListitems = new HashSet<PropertyCheckListitem>();
        }
    
        public System.Guid Id { get; set; }
        public string DisplayName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressLine4 { get; set; }
        public string AddressLine5 { get; set; }
        public string Postcode { get; set; }
        public System.Guid SellerCodeId { get; set; }
        public System.Guid BuyerCodeId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string RightMoveIdentifier { get; set; }
        public string RightMoveImageUrl { get; set; }
        public string RightMoveAskingPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyCheckListitem> PropertyCheckListitems { get; set; }
    }
}
