//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chains.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public System.Guid Id { get; set; }
        public string DisplayName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressLine4 { get; set; }
        public string AddressLine5 { get; set; }
        public string Postcode { get; set; }
        public System.Guid SellerCodeId { get; set; }
        public System.Guid BuyerCodeId { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string RightMoveIdentifier { get; set; }
    }
}
