//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chains.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyCheckListitem
    {
        public System.Guid Id { get; set; }
        public System.Guid PropertyId { get; set; }
        public System.Guid CheckListItemId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public Nullable<System.Guid> CompletedUserId { get; set; }
    
        public virtual CheckListItem CheckListItem { get; set; }
        public virtual Property Property { get; set; }
    }
}
