//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chains.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PublicUser()
        {
            this.CustomDefaultCheckLists = new HashSet<CustomDefaultCheckList>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid PublicUserTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomDefaultCheckList> CustomDefaultCheckLists { get; set; }
        public virtual PublicUserType PublicUserType { get; set; }
    }
}
